import { pgTable, text, timestamp, boolean, serial, integer, primaryKey } from "drizzle-orm/pg-core"

// --- Better Auth required tables -------------------------------------------
// Column names are camelCase to match Better Auth's defaults. Do not rename.

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("emailVerified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
  // username plugin
  username: text("username").unique(),
  displayUsername: text("displayUsername"),
  // admin plugin
  role: text("role"),
  banned: boolean("banned"),
  banReason: text("banReason"),
  banExpires: timestamp("banExpires"),
  // custom fine-grained permissions (JSON array string), e.g. ["manage_catalog","view_messages"]
  permissions: text("permissions"),
  // when true, the admin has locked this user out with a maintenance notice
  maintenance: boolean("maintenance").notNull().default(false),
  // Admin-recoverable copy of the current password, encrypted at rest with
  // AES-256-GCM (key derived from BETTER_AUTH_SECRET). Captured whenever a
  // password is set through the app (create / admin reset / self-service change)
  // so the owner can reveal it in the Usuarios panel. Passwords set before this
  // feature existed stay null until the user changes them.
  recoveryPassword: text("recoveryPassword"),
})

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expiresAt").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
  ipAddress: text("ipAddress"),
  userAgent: text("userAgent"),
  userId: text("userId")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  impersonatedBy: text("impersonatedBy"),
})

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("accountId").notNull(),
  providerId: text("providerId").notNull(),
  issuer: text("issuer"),
  userId: text("userId")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("accessToken"),
  refreshToken: text("refreshToken"),
  idToken: text("idToken"),
  accessTokenExpiresAt: timestamp("accessTokenExpiresAt"),
  refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
})

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expiresAt").notNull(),
  createdAt: timestamp("createdAt").defaultNow(),
  updatedAt: timestamp("updatedAt").defaultNow(),
})

// --- App tables ------------------------------------------------------------
// These are global, admin-managed resources (not per-user data). Access is
// controlled by the acting user's role/permissions, checked server-side.

export const equipment = pgTable("equipment", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  category: text("category").notNull().default(""),
  description: text("description").notNull().default(""),
  image: text("image").notNull().default(""),
  tag: text("tag").notNull().default(""),
  specs: text("specs").notNull().default(""),
  sortOrder: integer("sortOrder").notNull().default(0),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
})

// Per-language overrides for a piece of equipment. The base `equipment` row
// holds the Spanish (canonical) text plus language-neutral fields (image, tag,
// order, active). A missing translation falls back to the base row.
export const equipmentTranslation = pgTable(
  "equipment_translation",
  {
    equipmentId: integer("equipmentId")
      .notNull()
      .references(() => equipment.id, { onDelete: "cascade" }),
    lang: text("lang").notNull(),
    name: text("name").notNull().default(""),
    category: text("category").notNull().default(""),
    description: text("description").notNull().default(""),
    specs: text("specs").notNull().default(""),
    // true when generated by AI auto-translation, false when edited by an admin.
    auto: boolean("auto").notNull().default(false),
    updatedAt: timestamp("updatedAt").notNull().defaultNow(),
  },
  (t) => ({ pk: primaryKey({ columns: [t.equipmentId, t.lang] }) }),
)

  export const siteContent = pgTable(
  "site_content",
  {
  lang: text("lang").notNull().default("es"),
  key: text("key").notNull(),
  value: text("value").notNull().default(""),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
  },
  (t) => ({ pk: primaryKey({ columns: [t.lang, t.key] }) }),
  )

export const contactMessage = pgTable("contact_message", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().default(""),
  institution: text("institution").notNull().default(""),
  interest: text("interest").notNull().default(""),
  message: text("message").notNull().default(""),
  phone: text("phone").notNull().default(""),
  read: boolean("read").notNull().default(false),
  replied: boolean("replied").notNull().default(false),
  repliedAt: timestamp("repliedAt"),
  replyText: text("replyText").notNull().default(""),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
})

// Technical data sheets ("fichas técnicas") built from a fixed CAMVEX template.
// All sheets share the same layout; the dynamic fields below vary per product.
// JSON-encoded columns: characteristics = string[], applications = string[],
// specs = { param: string; value: string }[].
export const dataSheet = pgTable("data_sheet", {
  id: serial("id").primaryKey(),
  title: text("title").notNull().default(""),
  subtitle: text("subtitle").notNull().default(""),
  intro: text("intro").notNull().default(""),
  image: text("image").notNull().default(""),
  formula: text("formula").notNull().default(""),
  manufacturer: text("manufacturer").notNull().default(""),
  presentation: text("presentation").notNull().default(""),
  characteristics: text("characteristics").notNull().default("[]"),
  specs: text("specs").notNull().default("[]"),
  applications: text("applications").notNull().default("[]"),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
})

// Price quotations ("cotizaciones") built from a fixed CAMVEX template. Each
// quotation targets a client/company and lists line items. Money is computed
// from the items at render time; only inputs are stored. JSON-encoded column:
// items = { description: string; image: string; quantity: number; unitPrice: number }[].
export const quotation = pgTable("quotation", {
  id: serial("id").primaryKey(),
  number: text("number").notNull().default(""),
  clientName: text("clientName").notNull().default(""),
  clientContact: text("clientContact").notNull().default(""),
  clientEmail: text("clientEmail").notNull().default(""),
  clientPhone: text("clientPhone").notNull().default(""),
  title: text("title").notNull().default(""),
  // Who prepared the quotation (CAMVEX rep) + their contact info.
  preparedBy: text("preparedBy").notNull().default(""),
  preparedByContact: text("preparedByContact").notNull().default(""),
  currency: text("currency").notNull().default("DOP"), // DOP | USD
  taxEnabled: boolean("taxEnabled").notNull().default(true),
  taxRate: text("taxRate").notNull().default("18"),
  validityDays: integer("validityDays").notNull().default(15),
  notes: text("notes").notNull().default(""),
  items: text("items").notNull().default("[]"),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
})

// Strategic-alliance logos shown in the home-page ticker. Admin-managed:
// add, hide/show, reorder (sortOrder) and remove. Only active rows render
// on the public site, ordered by sortOrder ascending.
export const partner = pgTable("partner", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().default(""),
  image: text("image").notNull().default(""),
  active: boolean("active").notNull().default(true),
  sortOrder: integer("sortOrder").notNull().default(0),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
})

// Audit trail ("Caché"). One row per meaningful change made by a panel user
// (create/update/delete across catalog, sheets, quotations, messages, users,
// site content). Read-only from the UI and visible to admins only.
export const activityLog = pgTable("activity_log", {
  id: serial("id").primaryKey(),
  actorId: text("actorId").notNull().default(""),
  actorName: text("actorName").notNull().default(""),
  actorUsername: text("actorUsername").notNull().default(""),
  actorRole: text("actorRole").notNull().default(""),
  action: text("action").notNull().default(""), // created | updated | deleted
  entity: text("entity").notNull().default(""), // module label, e.g. "Catálogo"
  summary: text("summary").notNull().default(""),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
})
