// Complete country dial-code list for the contact form phone field.
// `min`/`max` are the accepted national (subscriber) number digit counts used
// to validate the entered number against the selected country.
export type Country = { iso: string; name: string; dial: string; min: number; max: number }

// Flag image URL from the flagcdn.com CDN. Emoji flags don't render on
// Windows/Chrome, so we use real PNG images that work on every platform.
// `w` is the CDN width bucket (20, 40, 80…); it serves crisp @2x for retina.
export function flagUrl(iso: string, w = 40): string {
  return `https://flagcdn.com/w${w}/${iso.toLowerCase()}.png`
}

// Names in Spanish (site default). Dominican Republic is the default selection.
export const COUNTRIES: Country[] = [
  { iso: "DO", name: "República Dominicana", dial: "1", min: 10, max: 10 },
  { iso: "AF", name: "Afganistán", dial: "93", min: 9, max: 9 },
  { iso: "AL", name: "Albania", dial: "355", min: 8, max: 9 },
  { iso: "DE", name: "Alemania", dial: "49", min: 10, max: 11 },
  { iso: "AD", name: "Andorra", dial: "376", min: 6, max: 6 },
  { iso: "AO", name: "Angola", dial: "244", min: 9, max: 9 },
  { iso: "AI", name: "Anguila", dial: "1", min: 10, max: 10 },
  { iso: "AG", name: "Antigua y Barbuda", dial: "1", min: 10, max: 10 },
  { iso: "SA", name: "Arabia Saudita", dial: "966", min: 9, max: 9 },
  { iso: "DZ", name: "Argelia", dial: "213", min: 9, max: 9 },
  { iso: "AR", name: "Argentina", dial: "54", min: 10, max: 11 },
  { iso: "AM", name: "Armenia", dial: "374", min: 8, max: 8 },
  { iso: "AW", name: "Aruba", dial: "297", min: 7, max: 7 },
  { iso: "AU", name: "Australia", dial: "61", min: 9, max: 9 },
  { iso: "AT", name: "Austria", dial: "43", min: 8, max: 13 },
  { iso: "AZ", name: "Azerbaiyán", dial: "994", min: 9, max: 9 },
  { iso: "BS", name: "Bahamas", dial: "1", min: 10, max: 10 },
  { iso: "BH", name: "Baréin", dial: "973", min: 8, max: 8 },
  { iso: "BD", name: "Bangladés", dial: "880", min: 10, max: 10 },
  { iso: "BB", name: "Barbados", dial: "1", min: 10, max: 10 },
  { iso: "BE", name: "Bélgica", dial: "32", min: 8, max: 9 },
  { iso: "BZ", name: "Belice", dial: "501", min: 7, max: 7 },
  { iso: "BJ", name: "Benín", dial: "229", min: 8, max: 8 },
  { iso: "BM", name: "Bermudas", dial: "1", min: 10, max: 10 },
  { iso: "BY", name: "Bielorrusia", dial: "375", min: 9, max: 9 },
  { iso: "BO", name: "Bolivia", dial: "591", min: 8, max: 8 },
  { iso: "BA", name: "Bosnia y Herzegovina", dial: "387", min: 8, max: 8 },
  { iso: "BW", name: "Botsuana", dial: "267", min: 7, max: 8 },
  { iso: "BR", name: "Brasil", dial: "55", min: 10, max: 11 },
  { iso: "BN", name: "Brunéi", dial: "673", min: 7, max: 7 },
  { iso: "BG", name: "Bulgaria", dial: "359", min: 8, max: 9 },
  { iso: "BF", name: "Burkina Faso", dial: "226", min: 8, max: 8 },
  { iso: "BI", name: "Burundi", dial: "257", min: 8, max: 8 },
  { iso: "BT", name: "Bután", dial: "975", min: 7, max: 8 },
  { iso: "CV", name: "Cabo Verde", dial: "238", min: 7, max: 7 },
  { iso: "KH", name: "Camboya", dial: "855", min: 8, max: 9 },
  { iso: "CM", name: "Camerún", dial: "237", min: 9, max: 9 },
  { iso: "CA", name: "Canadá", dial: "1", min: 10, max: 10 },
  { iso: "QA", name: "Catar", dial: "974", min: 8, max: 8 },
  { iso: "TD", name: "Chad", dial: "235", min: 8, max: 8 },
  { iso: "CL", name: "Chile", dial: "56", min: 9, max: 9 },
  { iso: "CN", name: "China", dial: "86", min: 11, max: 11 },
  { iso: "CY", name: "Chipre", dial: "357", min: 8, max: 8 },
  { iso: "VA", name: "Ciudad del Vaticano", dial: "39", min: 9, max: 10 },
  { iso: "CO", name: "Colombia", dial: "57", min: 10, max: 10 },
  { iso: "KM", name: "Comoras", dial: "269", min: 7, max: 7 },
  { iso: "CG", name: "Congo", dial: "242", min: 9, max: 9 },
  { iso: "CD", name: "Congo (RD)", dial: "243", min: 9, max: 9 },
  { iso: "KP", name: "Corea del Norte", dial: "850", min: 8, max: 10 },
  { iso: "KR", name: "Corea del Sur", dial: "82", min: 9, max: 10 },
  { iso: "CI", name: "Costa de Marfil", dial: "225", min: 10, max: 10 },
  { iso: "CR", name: "Costa Rica", dial: "506", min: 8, max: 8 },
  { iso: "HR", name: "Croacia", dial: "385", min: 8, max: 9 },
  { iso: "CU", name: "Cuba", dial: "53", min: 8, max: 8 },
  { iso: "CW", name: "Curazao", dial: "599", min: 7, max: 8 },
  { iso: "DK", name: "Dinamarca", dial: "45", min: 8, max: 8 },
  { iso: "DM", name: "Dominica", dial: "1", min: 10, max: 10 },
  { iso: "EC", name: "Ecuador", dial: "593", min: 9, max: 9 },
  { iso: "EG", name: "Egipto", dial: "20", min: 10, max: 10 },
  { iso: "SV", name: "El Salvador", dial: "503", min: 8, max: 8 },
  { iso: "AE", name: "Emiratos Árabes Unidos", dial: "971", min: 9, max: 9 },
  { iso: "ER", name: "Eritrea", dial: "291", min: 7, max: 7 },
  { iso: "SK", name: "Eslovaquia", dial: "421", min: 9, max: 9 },
  { iso: "SI", name: "Eslovenia", dial: "386", min: 8, max: 8 },
  { iso: "ES", name: "España", dial: "34", min: 9, max: 9 },
  { iso: "US", name: "Estados Unidos", dial: "1", min: 10, max: 10 },
  { iso: "EE", name: "Estonia", dial: "372", min: 7, max: 8 },
  { iso: "SZ", name: "Esuatini", dial: "268", min: 8, max: 8 },
  { iso: "ET", name: "Etiopía", dial: "251", min: 9, max: 9 },
  { iso: "PH", name: "Filipinas", dial: "63", min: 10, max: 10 },
  { iso: "FI", name: "Finlandia", dial: "358", min: 9, max: 10 },
  { iso: "FJ", name: "Fiyi", dial: "679", min: 7, max: 7 },
  { iso: "FR", name: "Francia", dial: "33", min: 9, max: 9 },
  { iso: "GA", name: "Gabón", dial: "241", min: 7, max: 8 },
  { iso: "GM", name: "Gambia", dial: "220", min: 7, max: 7 },
  { iso: "GE", name: "Georgia", dial: "995", min: 9, max: 9 },
  { iso: "GH", name: "Ghana", dial: "233", min: 9, max: 9 },
  { iso: "GI", name: "Gibraltar", dial: "350", min: 8, max: 8 },
  { iso: "GD", name: "Granada", dial: "1", min: 10, max: 10 },
  { iso: "GR", name: "Grecia", dial: "30", min: 10, max: 10 },
  { iso: "GL", name: "Groenlandia", dial: "299", min: 6, max: 6 },
  { iso: "GP", name: "Guadalupe", dial: "590", min: 9, max: 9 },
  { iso: "GU", name: "Guam", dial: "1", min: 10, max: 10 },
  { iso: "GT", name: "Guatemala", dial: "502", min: 8, max: 8 },
  { iso: "GF", name: "Guayana Francesa", dial: "594", min: 9, max: 9 },
  { iso: "GN", name: "Guinea", dial: "224", min: 9, max: 9 },
  { iso: "GQ", name: "Guinea Ecuatorial", dial: "240", min: 9, max: 9 },
  { iso: "GW", name: "Guinea-Bisáu", dial: "245", min: 7, max: 7 },
  { iso: "GY", name: "Guyana", dial: "592", min: 7, max: 7 },
  { iso: "HT", name: "Haití", dial: "509", min: 8, max: 8 },
  { iso: "HN", name: "Honduras", dial: "504", min: 8, max: 8 },
  { iso: "HK", name: "Hong Kong", dial: "852", min: 8, max: 8 },
  { iso: "HU", name: "Hungría", dial: "36", min: 8, max: 9 },
  { iso: "IN", name: "India", dial: "91", min: 10, max: 10 },
  { iso: "ID", name: "Indonesia", dial: "62", min: 9, max: 11 },
  { iso: "IQ", name: "Irak", dial: "964", min: 10, max: 10 },
  { iso: "IR", name: "Irán", dial: "98", min: 10, max: 10 },
  { iso: "IE", name: "Irlanda", dial: "353", min: 9, max: 9 },
  { iso: "IS", name: "Islandia", dial: "354", min: 7, max: 7 },
  { iso: "KY", name: "Islas Caimán", dial: "1", min: 10, max: 10 },
  { iso: "CK", name: "Islas Cook", dial: "682", min: 5, max: 5 },
  { iso: "FO", name: "Islas Feroe", dial: "298", min: 6, max: 6 },
  { iso: "MP", name: "Islas Marianas del Norte", dial: "1", min: 10, max: 10 },
  { iso: "MH", name: "Islas Marshall", dial: "692", min: 7, max: 7 },
  { iso: "SB", name: "Islas Salomón", dial: "677", min: 7, max: 7 },
  { iso: "TC", name: "Islas Turcas y Caicos", dial: "1", min: 10, max: 10 },
  { iso: "VG", name: "Islas Vírgenes Británicas", dial: "1", min: 10, max: 10 },
  { iso: "VI", name: "Islas Vírgenes de EE. UU.", dial: "1", min: 10, max: 10 },
  { iso: "IL", name: "Israel", dial: "972", min: 9, max: 9 },
  { iso: "IT", name: "Italia", dial: "39", min: 9, max: 10 },
  { iso: "JM", name: "Jamaica", dial: "1", min: 10, max: 10 },
  { iso: "JP", name: "Japón", dial: "81", min: 10, max: 10 },
  { iso: "JO", name: "Jordania", dial: "962", min: 9, max: 9 },
  { iso: "KZ", name: "Kazajistán", dial: "7", min: 10, max: 10 },
  { iso: "KE", name: "Kenia", dial: "254", min: 9, max: 9 },
  { iso: "KG", name: "Kirguistán", dial: "996", min: 9, max: 9 },
  { iso: "KI", name: "Kiribati", dial: "686", min: 5, max: 8 },
  { iso: "KW", name: "Kuwait", dial: "965", min: 8, max: 8 },
  { iso: "LA", name: "Laos", dial: "856", min: 8, max: 10 },
  { iso: "LS", name: "Lesoto", dial: "266", min: 8, max: 8 },
  { iso: "LV", name: "Letonia", dial: "371", min: 8, max: 8 },
  { iso: "LB", name: "Líbano", dial: "961", min: 7, max: 8 },
  { iso: "LR", name: "Liberia", dial: "231", min: 7, max: 9 },
  { iso: "LY", name: "Libia", dial: "218", min: 9, max: 9 },
  { iso: "LI", name: "Liechtenstein", dial: "423", min: 7, max: 7 },
  { iso: "LT", name: "Lituania", dial: "370", min: 8, max: 8 },
  { iso: "LU", name: "Luxemburgo", dial: "352", min: 9, max: 9 },
  { iso: "MO", name: "Macao", dial: "853", min: 8, max: 8 },
  { iso: "MK", name: "Macedonia del Norte", dial: "389", min: 8, max: 8 },
  { iso: "MG", name: "Madagascar", dial: "261", min: 9, max: 9 },
  { iso: "MY", name: "Malasia", dial: "60", min: 9, max: 10 },
  { iso: "MW", name: "Malaui", dial: "265", min: 9, max: 9 },
  { iso: "MV", name: "Maldivas", dial: "960", min: 7, max: 7 },
  { iso: "ML", name: "Malí", dial: "223", min: 8, max: 8 },
  { iso: "MT", name: "Malta", dial: "356", min: 8, max: 8 },
  { iso: "MA", name: "Marruecos", dial: "212", min: 9, max: 9 },
  { iso: "MQ", name: "Martinica", dial: "596", min: 9, max: 9 },
  { iso: "MU", name: "Mauricio", dial: "230", min: 7, max: 8 },
  { iso: "MR", name: "Mauritania", dial: "222", min: 8, max: 8 },
  { iso: "MX", name: "México", dial: "52", min: 10, max: 10 },
  { iso: "FM", name: "Micronesia", dial: "691", min: 7, max: 7 },
  { iso: "MD", name: "Moldavia", dial: "373", min: 8, max: 8 },
  { iso: "MC", name: "Mónaco", dial: "377", min: 8, max: 9 },
  { iso: "MN", name: "Mongolia", dial: "976", min: 8, max: 8 },
  { iso: "ME", name: "Montenegro", dial: "382", min: 8, max: 8 },
  { iso: "MS", name: "Montserrat", dial: "1", min: 10, max: 10 },
  { iso: "MZ", name: "Mozambique", dial: "258", min: 9, max: 9 },
  { iso: "MM", name: "Myanmar", dial: "95", min: 8, max: 10 },
  { iso: "NA", name: "Namibia", dial: "264", min: 9, max: 9 },
  { iso: "NR", name: "Nauru", dial: "674", min: 7, max: 7 },
  { iso: "NP", name: "Nepal", dial: "977", min: 10, max: 10 },
  { iso: "NI", name: "Nicaragua", dial: "505", min: 8, max: 8 },
  { iso: "NE", name: "Níger", dial: "227", min: 8, max: 8 },
  { iso: "NG", name: "Nigeria", dial: "234", min: 8, max: 10 },
  { iso: "NO", name: "Noruega", dial: "47", min: 8, max: 8 },
  { iso: "NC", name: "Nueva Caledonia", dial: "687", min: 6, max: 6 },
  { iso: "NZ", name: "Nueva Zelanda", dial: "64", min: 8, max: 10 },
  { iso: "OM", name: "Omán", dial: "968", min: 8, max: 8 },
  { iso: "NL", name: "Países Bajos", dial: "31", min: 9, max: 9 },
  { iso: "PK", name: "Pakistán", dial: "92", min: 10, max: 10 },
  { iso: "PW", name: "Palaos", dial: "680", min: 7, max: 7 },
  { iso: "PS", name: "Palestina", dial: "970", min: 9, max: 9 },
  { iso: "PA", name: "Panamá", dial: "507", min: 8, max: 8 },
  { iso: "PG", name: "Papúa Nueva Guinea", dial: "675", min: 8, max: 8 },
  { iso: "PY", name: "Paraguay", dial: "595", min: 9, max: 9 },
  { iso: "PE", name: "Perú", dial: "51", min: 9, max: 9 },
  { iso: "PF", name: "Polinesia Francesa", dial: "689", min: 6, max: 6 },
  { iso: "PL", name: "Polonia", dial: "48", min: 9, max: 9 },
  { iso: "PT", name: "Portugal", dial: "351", min: 9, max: 9 },
  { iso: "PR", name: "Puerto Rico", dial: "1", min: 10, max: 10 },
  { iso: "GB", name: "Reino Unido", dial: "44", min: 10, max: 10 },
  { iso: "CF", name: "República Centroafricana", dial: "236", min: 8, max: 8 },
  { iso: "CZ", name: "República Checa", dial: "420", min: 9, max: 9 },
  { iso: "RE", name: "Reunión", dial: "262", min: 9, max: 9 },
  { iso: "RW", name: "Ruanda", dial: "250", min: 9, max: 9 },
  { iso: "RO", name: "Rumanía", dial: "40", min: 9, max: 9 },
  { iso: "RU", name: "Rusia", dial: "7", min: 10, max: 10 },
  { iso: "WS", name: "Samoa", dial: "685", min: 5, max: 7 },
  { iso: "AS", name: "Samoa Americana", dial: "1", min: 10, max: 10 },
  { iso: "KN", name: "San Cristóbal y Nieves", dial: "1", min: 10, max: 10 },
  { iso: "SM", name: "San Marino", dial: "378", min: 10, max: 10 },
  { iso: "PM", name: "San Pedro y Miquelón", dial: "508", min: 6, max: 6 },
  { iso: "VC", name: "San Vicente y las Granadinas", dial: "1", min: 10, max: 10 },
  { iso: "LC", name: "Santa Lucía", dial: "1", min: 10, max: 10 },
  { iso: "ST", name: "Santo Tomé y Príncipe", dial: "239", min: 7, max: 7 },
  { iso: "SN", name: "Senegal", dial: "221", min: 9, max: 9 },
  { iso: "RS", name: "Serbia", dial: "381", min: 8, max: 9 },
  { iso: "SC", name: "Seychelles", dial: "248", min: 7, max: 7 },
  { iso: "SL", name: "Sierra Leona", dial: "232", min: 8, max: 8 },
  { iso: "SG", name: "Singapur", dial: "65", min: 8, max: 8 },
  { iso: "SY", name: "Siria", dial: "963", min: 9, max: 9 },
  { iso: "SO", name: "Somalia", dial: "252", min: 7, max: 8 },
  { iso: "LK", name: "Sri Lanka", dial: "94", min: 9, max: 9 },
  { iso: "ZA", name: "Sudáfrica", dial: "27", min: 9, max: 9 },
  { iso: "SD", name: "Sudán", dial: "249", min: 9, max: 9 },
  { iso: "SS", name: "Sudán del Sur", dial: "211", min: 9, max: 9 },
  { iso: "SE", name: "Suecia", dial: "46", min: 7, max: 9 },
  { iso: "CH", name: "Suiza", dial: "41", min: 9, max: 9 },
  { iso: "SR", name: "Surinam", dial: "597", min: 6, max: 7 },
  { iso: "TH", name: "Tailandia", dial: "66", min: 9, max: 9 },
  { iso: "TW", name: "Taiwán", dial: "886", min: 9, max: 9 },
  { iso: "TZ", name: "Tanzania", dial: "255", min: 9, max: 9 },
  { iso: "TJ", name: "Tayikistán", dial: "992", min: 9, max: 9 },
  { iso: "TL", name: "Timor Oriental", dial: "670", min: 7, max: 8 },
  { iso: "TG", name: "Togo", dial: "228", min: 8, max: 8 },
  { iso: "TO", name: "Tonga", dial: "676", min: 5, max: 7 },
  { iso: "TT", name: "Trinidad y Tobago", dial: "1", min: 10, max: 10 },
  { iso: "TN", name: "Túnez", dial: "216", min: 8, max: 8 },
  { iso: "TM", name: "Turkmenistán", dial: "993", min: 8, max: 8 },
  { iso: "TR", name: "Turquía", dial: "90", min: 10, max: 10 },
  { iso: "TV", name: "Tuvalu", dial: "688", min: 5, max: 6 },
  { iso: "UA", name: "Ucrania", dial: "380", min: 9, max: 9 },
  { iso: "UG", name: "Uganda", dial: "256", min: 9, max: 9 },
  { iso: "UY", name: "Uruguay", dial: "598", min: 8, max: 8 },
  { iso: "UZ", name: "Uzbekistán", dial: "998", min: 9, max: 9 },
  { iso: "VU", name: "Vanuatu", dial: "678", min: 5, max: 7 },
  { iso: "VE", name: "Venezuela", dial: "58", min: 10, max: 10 },
  { iso: "VN", name: "Vietnam", dial: "84", min: 9, max: 10 },
  { iso: "YE", name: "Yemen", dial: "967", min: 7, max: 9 },
  { iso: "DJ", name: "Yibuti", dial: "253", min: 8, max: 8 },
  { iso: "ZM", name: "Zambia", dial: "260", min: 9, max: 9 },
  { iso: "ZW", name: "Zimbabue", dial: "263", min: 9, max: 9 },
]
